canonifyurls = true
languageCode = "en-us"
title = "Tech @ SparkFabrik"

[Params]
  logo = "img/sfgear.png"
  description = "Sparkfabrik tech blog"

  [Params.Authors]
    [Params.Authors.Stick]
      name = "Paolo Pustorino"
      role = "CEO"
      picture = "http://www.sparkfabrik.com/images/team/pusto.png"
      bio = "Drummer, tabletop role-player and developer. Incidentally CEO and striving servant leader from 2013."
      github = "http://www.github.com/stickgrinder"
      twitter = "http://www.twitter.com/stickgrinder"

    [Params.Authors.Paolo]
      name = "Paolo Mainardi"
      role = "CTO"
      picture = "http://www.sparkfabrik.com/images/team/paolo.jpg"
      bio = "Hacker, open-source enthusiast, reddit addicted and now proud founder of Sparkfabrik."
      github = "http://www.github.com/paolomainardi"
      twitter = "http://www.twitter.com/paolomainardi"

    [Params.Authors.Pinolo]
      name = "Marcello Testi"
      role = "Lead Developer"
      picture = "http://www.sparkfabrik.com/images/team/pinolo.jpg"
      bio = "Long-time open-source contributor, avid music listener. In Sparkfabrik since day-1."
      github = "http://www.github.com/pinolo"
      twitter = "http://www.twitter.com/pinolo"


[Author]
  name = "Sparkfabrik"
  email = "info@sparkfabrik.com"
  facebook = "sparkfabrik"
  twitter = "sparkfabrik"
  phone = "+39-02-83631284"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Team"
    url = "/page/team/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 3

[permalinks]
    post = "/:year/:month/:day/:slug"
